import { Roboto } from "next/font/google";
import Header from "@components/Header";
import "@styles/global.css"

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
  title: "Blog page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} page_padding`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
